# Test our Ansible role

Vagrant.configure("2") do |config|
  # Ubuntu Bionic 18.04
  #config.vm.box = "ubuntu/bionic64"
  # CentOS 7
  #config.vm.box = "centos/7"
  # Ubuntu Xenial 16.04
  config.vm.box = "ubuntu/xenial64"
  config.vm.network "private_network", ip: "10.0.3.5",
   auto_config: false


  # Trigger ansible playbook build
  config.vm.provision "ansible" do |ansible|
    # Run playbook
    ansible.playbook = "test.yml"
  end
end
